version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: financial_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: financial_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  postgres-data: